travis:
  secure:
    BINSTAR_TOKEN: LGXKcR6XJxvCAjvaQREeI/4hxw/qgCEQxrn/8ZHeXTSGcI8DXXbDxAK0Ns2N4XJfxAVHA9PCiWuOTvYqq2dQFJ7gMp5jg+QS7DL3xegZ2Gr/VEPs5TKQiQBethPWm4Q+uKkti4FXJInN4YR7rV5t5HwOLJM3ItB8Fbt3XiAyd3xZ2VkJ+wum2+VrpGPowWzRPteJuH6uHq2GQ/pNByKBHyJCK4AiF0OnoMdhFOIL+GEmVd8CdVRn+L2cf/cLHGS3BVyN6LQK6/mdiC5wCPTRaf0JVm3e+ZlKwQ/E4VvXXX5q8ShBUNZRF/PohtJ+5AFJdOCLFapczN2SAZ63po+XpYcDGZNlT6i2fjhq1b77x3weJ3CXQKwzW3kHD/dOBf/E2ZpNZ1TqbyNMfQrv+4cfP7gdzie/CnhOKYSX4lRSvG1QWYkuvhPs7bGX+uPXKqM7hwcpRXYH9GKCxNmktS9RXsRmtuX206qXQhPdfVq68obr7MvuvtkPjAPQj3znd8mOksjFjSRRGg78BquDKXytM3OFFVgzm86ge9Fwv9i971w8US+A6ZLnRppFt/38CDxvi0SAxQBd35ynA8waXc7lp9WH3BGRFFDA0s+mmqWEdfCBARrhA4FomImXNTFR03U3sVjfPxPl19Ds1NzUYPONgR+SQx6ZPCtzFTQAVIOJR24=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
